name: whispr_chat_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.11
  google_fonts: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_messaging: ^15.2.3
  cloud_firestore: ^5.6.4
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Storage & State Management
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7
  
  # Time Formatting
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/splash_logo.png
  #   - assets/logo.png
  #   # - assets/chat_background.jpg



# Splash screen configuration
flutter_native_splash:
  color: "#6366F1"
  # color_dark: "#1E293B"
  image: assets/splash_logo.png
  
  android_12:
    color: "#6366F1"
    # color_dark: "#1E293B"
    image: assets/splash_logo.png
    icon_background_color: "#6366F1"
    # icon_background_color_dark: "#1E293B"

  android: true
  ios: true
  web: true
  
  fullscreen: true